### ISSUE TITLE
Github repo

### ISSUE THREAD

**Issue by FranciscoRam** [UG-Cloud-Computing-2016-Semester1/Tareas#3]
Sobre el repositorio me esta cusando unos problemas y no se bien por que. Me sale cuando le pongo 
git status.
On branch master
nothing to commit, working directory clean

**Comment by FranciscoRam** [comment]
hice otra carpeta y ya no me aparecio el problema antes mencionado pero ahora me sale cuando le doy git push -u origin master 
error: src refspect master does not match any
error> failed to push some refs to `https://github.com/FranciscoRam/NodeSchool-Solution.git`

**Comment by JuanCrg90** [comment]
http://stackoverflow.com/questions/4181861/src-refspec-master-does-not-match-any-when-pushing-commits-in-git

**Comment by FranciscoRam** [comment]
Muchas gracias me sirvio de mucho

2016-02-24 4:21 GMT+00:00 Juan Carlos Ruiz González <
notifications@github.com>:
